import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <div className='container'>
                <h1>Index</h1>
                <Link href='/auth'>
                    <a>Auth</a>
                </Link>
            </div>
        </div>
    );
};

export default Home;
